import { createHash } from 'node:crypto';
import { parseCaseBundle, type CaseBundle } from './case.js';

/**
 * Fixture-only dataset for the Phase 0/1 gates. Every URI is non-resolvable
 * by construction and every digest is computed from the fixture text, so a test
 * run never touches the network or a real program. There are no live targets
 * here by design (evaluation plan, evaluation fixtures).
 */

export const FIXTURE_PROGRAM = 'example-inhouse-program';
export const FIXTURE_NOW = '2026-09-30T12:00:00Z';
export const FIXTURE_POLICY_MAX_AGE_DAYS = 90;

const digestOf = (content: string): string =>
  `sha256:${createHash('sha256').update(content).digest('hex')}`;

const currentPolicyText = [
  'example-inhouse-program policy snapshot 2026-09',
  'in scope: https://example.invalid/programs/checkout-service/',
  'out of scope: https://example.invalid/programs/checkout-service/vendor-portal/',
].join('\n');

const stalePolicyText = [
  'example-inhouse-program policy snapshot 2025-01',
  'in scope: https://example.invalid/programs/checkout-service/',
].join('\n');

export const fixtureBundleJson: Record<string, unknown> = {
  version: 1,
  scope: [
    {
      version: 1,
      program: FIXTURE_PROGRAM,
      policyUrl: 'https://example.invalid/policies/example-inhouse-program',
      inScope: ['https://example.invalid/programs/checkout-service'],
      outOfScope: ['https://example.invalid/programs/checkout-service/vendor-portal'],
    },
  ],
  programs: [
    {
      version: 1,
      programId: FIXTURE_PROGRAM,
      displayName: 'Example in-house program',
      policySnapshotId: 'src-policy-current',
      bountyAssetTypes: ['web-application', 'api'],
      rewardSchedulePublished:
        'Quoted from the 2026-09 snapshot: "USD 500 to USD 2500 per accepted report, set by severity category".',
      rewardCategoriesPublished: ['informational', 'low', 'medium', 'high', 'critical'],
      reportRequirements: [
        'Include a reproducible request and response pair',
        'Name the exact asset and the version tested',
      ],
      testingConstraints: [
        'No denial-of-service testing',
        'No access to production customer data',
      ],
      severityRubric: 'local://policies/example-inhouse-program/2026-09.json#severity',
      capturedAt: '2026-09-28T10:00:00Z',
    },
  ],
  sources: [
    {
      version: 1,
      sourceId: 'src-policy-current',
      uri: 'local://policies/example-inhouse-program/2026-09.json',
      owner: 'operator',
      kind: 'policy_snapshot',
      observedAt: '2026-09-28T09:00:00Z',
      policyVersion: '2026-09',
      contentDigest: digestOf(currentPolicyText),
      retention: 'case_metadata',
    },
    {
      version: 1,
      sourceId: 'src-policy-stale',
      uri: 'local://policies/example-inhouse-program/2025-01.json',
      owner: 'operator',
      kind: 'policy_snapshot',
      observedAt: '2025-01-05T09:00:00Z',
      policyVersion: '2025-01',
      contentDigest: digestOf(stalePolicyText),
      retention: 'case_metadata',
    },
    {
      version: 1,
      sourceId: 'src-scanner-output',
      uri: 'file://reports/fixture-scan.json',
      kind: 'scanner_output',
      observedAt: '2026-09-27T18:30:00Z',
      contentDigest: digestOf('fixture scanner output for the checkout service'),
      retention: 'transient',
    },
    {
      version: 1,
      sourceId: 'src-fixture-notes',
      uri: 'file://notes/fixture-notes.md',
      kind: 'fixture',
      observedAt: '2026-09-29T20:00:00Z',
      contentDigest: digestOf('fixture notes describing an unverified lead'),
      retention: 'case_metadata',
    },
    {
      version: 1,
      sourceId: 'src-operator-receipt',
      uri: 'file://receipts/fixture-receipt.txt',
      owner: 'operator',
      kind: 'operator_note',
      observedAt: '2026-09-10T11:00:00Z',
      contentDigest: digestOf('fixture receipt confirming a payout'),
      retention: 'operator_archive',
    },
  ],
  cases: [
    {
      version: 1,
      caseId: 'case-exact-in-scope',
      objective: 'Confirm the checkout service is in scope and evidence-backed before any owner review',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:00:00Z',
      state: 'research',
    },
    {
      version: 1,
      caseId: 'case-excluded-subdomain',
      objective: 'Check a vendored portal that the policy lists as excluded',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service/vendor-portal/console',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:05:00Z',
      state: 'intake',
    },
    {
      version: 1,
      caseId: 'case-stale-policy',
      objective: 'Re-check a lead recorded against a policy snapshot that is now stale',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service/legacy',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-stale',
      createdAt: '2025-01-06T08:00:00Z',
      state: 'intake',
    },
    {
      version: 1,
      caseId: 'case-no-evidence',
      objective: 'Record a lead that has no deterministic evidence behind it',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service/unverified',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:10:00Z',
      state: 'intake',
    },
    {
      version: 1,
      caseId: 'case-wildcard-asset',
      objective: 'Handle a lead whose asset was recorded as a pattern rather than a repository',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-*',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:15:00Z',
      state: 'intake',
    },
    {
      version: 1,
      caseId: 'case-similar-asset',
      objective: 'Tell apart an asset whose name is a near miss for an in-scope one',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service-legacy',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:20:00Z',
      state: 'intake',
    },
    {
      version: 1,
      caseId: 'case-no-bounty-asset-type',
      objective: 'Check an in-scope asset whose class the program does not pay for',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service/token-issuer',
      assetType: 'smart-contract',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:25:00Z',
      state: 'intake',
    },
    {
      version: 1,
      caseId: 'case-ambiguous-asset',
      objective: 'Handle an asset recorded on a host that cannot be told apart from an internal one',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://intranet/programs/checkout-service',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:30:00Z',
      state: 'intake',
    },
    {
      version: 1,
      caseId: 'case-duplicate-lead',
      objective: 'Compare a session-fixation lead against an existing case before it reaches the owner',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service/session-fixation',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:35:00Z',
      state: 'research',
    },
    {
      version: 1,
      caseId: 'case-unconfirmed',
      objective: 'Show a fully evidenced in-scope lead that no human has confirmed yet',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service/rate-limit',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:40:00Z',
      state: 'awaiting_owner',
    },
    {
      version: 1,
      caseId: 'case-stale-confirmation',
      objective: 'Show a lead confirmed against a policy snapshot that is no longer the current one',
      programId: FIXTURE_PROGRAM,
      assetOriginal: 'https://example.invalid/programs/checkout-service/redirect-loop',
      assetType: 'web-application',
      policySnapshotId: 'src-policy-current',
      createdAt: '2026-09-29T08:45:00Z',
      state: 'awaiting_owner',
    },
  ],
  evidence: [
    {
      version: 1,
      evidenceId: 'ev-scope-match',
      caseId: 'case-exact-in-scope',
      claim: 'The checkout service host is listed in the 2026-09 policy snapshot as in scope',
      claimType: 'fact',
      sourceId: 'src-policy-current',
      observedAt: '2026-09-28T09:05:00Z',
      confidenceReason: 'Deterministic match against the snapshot digest recorded by the operator',
      verification: 'deterministic',
    },
    {
      version: 1,
      evidenceId: 'ev-scanner-hypothesis',
      caseId: 'case-exact-in-scope',
      claim: 'The scanner report suggests a misconfigured cache header on one route',
      claimType: 'hypothesis',
      sourceId: 'src-scanner-output',
      observedAt: '2026-09-27T18:35:00Z',
      confidenceReason: 'Scanner heuristic only; no independent reproduction yet',
      verification: 'unverified',
    },
    {
      version: 1,
      evidenceId: 'ev-excluded',
      caseId: 'case-excluded-subdomain',
      claim: 'The vendor portal path is excluded by the 2026-09 policy snapshot',
      claimType: 'fact',
      sourceId: 'src-policy-current',
      observedAt: '2026-09-28T09:05:00Z',
      confidenceReason: 'Deterministic match against the snapshot exclusion list',
      verification: 'deterministic',
    },
    {
      version: 1,
      evidenceId: 'ev-stale-snapshot',
      caseId: 'case-stale-policy',
      claim: 'The 2025-01 snapshot listed the legacy route as in scope',
      claimType: 'fact',
      sourceId: 'src-policy-stale',
      observedAt: '2025-01-05T09:05:00Z',
      confidenceReason: 'Read from the archived snapshot; the snapshot itself may be out of date',
      verification: 'operator_confirmed',
    },
    {
      version: 1,
      evidenceId: 'ev-unverified-lead',
      caseId: 'case-no-evidence',
      claim: 'A teammate believes the unverified route mishandles a header',
      claimType: 'hypothesis',
      sourceId: 'src-fixture-notes',
      observedAt: '2026-09-29T20:05:00Z',
      confidenceReason: 'Second-hand note with no reproduction and no scanner corroboration',
      verification: 'unverified',
    },
    {
      version: 1,
      evidenceId: 'ev-repro-cache-header',
      caseId: 'case-exact-in-scope',
      claim: 'The cache header is reproduced from the saved scanner response, independent of the scanner run',
      claimType: 'fact',
      sourceId: 'src-scanner-output',
      observedAt: '2026-09-28T07:00:00Z',
      confidenceReason: 'Deterministic replay of the recorded response against the fixture artifact',
      verification: 'deterministic',
    },
    {
      version: 1,
      evidenceId: 'ev-duplicate-scope-match',
      caseId: 'case-duplicate-lead',
      claim: 'The session-fixation route is listed in the 2026-09 policy snapshot as in scope',
      claimType: 'fact',
      sourceId: 'src-policy-current',
      observedAt: '2026-09-28T09:10:00Z',
      confidenceReason: 'Deterministic match against the snapshot digest recorded by the operator',
      verification: 'deterministic',
    },
    {
      version: 1,
      evidenceId: 'ev-unconfirmed-scope-match',
      caseId: 'case-unconfirmed',
      claim: 'The rate-limit route is listed in the 2026-09 policy snapshot as in scope',
      claimType: 'fact',
      sourceId: 'src-policy-current',
      observedAt: '2026-09-28T09:15:00Z',
      confidenceReason: 'Deterministic match against the snapshot digest recorded by the operator',
      verification: 'deterministic',
    },
    {
      version: 1,
      evidenceId: 'ev-stale-confirmation-scope-match',
      caseId: 'case-stale-confirmation',
      claim: 'The redirect-loop route is listed in the 2026-09 policy snapshot as in scope',
      claimType: 'fact',
      sourceId: 'src-policy-current',
      observedAt: '2026-09-28T09:20:00Z',
      confidenceReason: 'Deterministic match against the snapshot digest recorded by the operator',
      verification: 'deterministic',
    },
  ],
  tasks: [
    {
      version: 1,
      taskId: 'task-scope-observe',
      caseId: 'case-exact-in-scope',
      role: 'scout',
      goal: 'Resolve the asset against the recorded policy snapshot only',
      readRefs: ['ev-scope-match'],
      writablePaths: [],
      capability: 'observe',
      acceptanceChecks: ['No request leaves the local machine', 'Asset match is reported with the snapshot id'],
      provenanceRequired: true,
      outputSchemaVersion: 1,
    },
    {
      version: 1,
      taskId: 'task-evidence-analyze',
      caseId: 'case-exact-in-scope',
      role: 'analyst',
      goal: 'Separate the deterministic scope fact from the scanner hypothesis',
      workspaceRef: 'local://workspaces/case-exact-in-scope',
      readRefs: ['ev-scope-match', 'ev-scanner-hypothesis'],
      writablePaths: [],
      capability: 'analyze',
      acceptanceChecks: ['Hypothesis stays labelled unverified', 'Every claim cites an evidence id'],
      costBudgetUsd: 0.5,
      provenanceRequired: true,
      outputSchemaVersion: 1,
    },
    {
      version: 1,
      taskId: 'task-draft-patch',
      caseId: 'case-exact-in-scope',
      role: 'engineer',
      goal: 'Draft a bounded patch for owner review without applying it',
      workspaceRef: 'local://workspaces/case-exact-in-scope',
      readRefs: ['ev-scanner-hypothesis'],
      writablePaths: ['patches/cache-header.diff'],
      capability: 'modify',
      acceptanceChecks: ['Diff is proposed for review', 'Nothing is submitted anywhere'],
      provenanceRequired: true,
      outputSchemaVersion: 1,
    },
  ],
  approvals: [
    {
      version: 1,
      approvalId: 'ap-draft-patch',
      caseId: 'case-exact-in-scope',
      taskId: 'task-draft-patch',
      effect: 'apply the proposed diff to a local scratch copy only',
      payloadDigest: digestOf('patches/cache-header.diff proposal 1'),
      decision: 'approved',
      decidedBy: 'human',
      decidedAt: '2026-09-29T10:00:00Z',
      rationale: 'Operator reviewed the diff scope locally',
    },
  ],
  confirmations: [
    {
      version: 1,
      confirmationId: 'cf-exact-in-scope',
      caseId: 'case-exact-in-scope',
      confirmedBy: 'human',
      confirmedAt: '2026-09-29T09:30:00Z',
      policySnapshotId: 'src-policy-current',
      asset: 'https://example.invalid/programs/checkout-service',
      statement: 'Read the 2026-09 snapshot and confirmed this repository is the in-scope asset',
    },
    {
      version: 1,
      confirmationId: 'cf-duplicate-lead',
      caseId: 'case-duplicate-lead',
      confirmedBy: 'human',
      confirmedAt: '2026-09-29T09:40:00Z',
      policySnapshotId: 'src-policy-current',
      asset: 'https://example.invalid/programs/checkout-service/session-fixation',
      statement: 'Confirmed the route is in scope; the duplicate question is separate and unresolved',
    },
    {
      version: 1,
      confirmationId: 'cf-stale-snapshot',
      caseId: 'case-stale-confirmation',
      confirmedBy: 'human',
      confirmedAt: '2025-01-06T09:00:00Z',
      policySnapshotId: 'src-policy-stale',
      asset: 'https://example.invalid/programs/checkout-service/redirect-loop',
      statement: 'Confirmed against the 2025-01 snapshot, before the current snapshot was captured',
    },
  ],
  duplicateSearches: [
    {
      version: 1,
      searchId: 'ds-exact-in-scope',
      caseId: 'case-exact-in-scope',
      searchedAt: '2026-09-29T09:20:00Z',
      surfaceCovered: 'fixture duplicate index at example.invalid',
      similarityCaveat: 'An empty result is not proof that no duplicate exists',
      matchedCaseIds: [],
      performedBy: 'human',
    },
    {
      version: 1,
      searchId: 'ds-duplicate-lead',
      caseId: 'case-duplicate-lead',
      searchedAt: '2026-09-29T09:25:00Z',
      surfaceCovered: 'fixture duplicate index at example.invalid',
      similarityCaveat: 'A match is a lead to read, not a decision to discard the lead',
      matchedCaseIds: ['case-exact-in-scope'],
      performedBy: 'human',
    },
  ],
  assessments: [
    {
      version: 1,
      assessmentId: 'as-exact-impact',
      caseId: 'case-exact-in-scope',
      factor: 'impact_fit',
      level: 'medium',
      basis: 'Operator mapped this to the published medium category in the 2026-09 severity rubric',
      refId: FIXTURE_PROGRAM,
      assessedBy: 'human',
      assessedAt: '2026-09-29T10:30:00Z',
    },
    {
      version: 1,
      assessmentId: 'as-exact-effort',
      caseId: 'case-exact-in-scope',
      factor: 'effort',
      level: 'low',
      basis: 'Coarse operator estimate from the reproduced response; not a cost or a deadline promise',
      refId: 'ev-repro-cache-header',
      assessedBy: 'human',
      assessedAt: '2026-09-29T10:35:00Z',
    },
    {
      version: 1,
      assessmentId: 'as-exact-novelty',
      caseId: 'case-exact-in-scope',
      factor: 'novelty',
      level: 'high',
      basis: 'Claimed as high because a duplicate search found nothing',
      refId: 'ds-exact-in-scope',
      assessedBy: 'human',
      assessedAt: '2026-09-29T10:40:00Z',
    },
  ],
  outcomes: [
    {
      version: 1,
      outcomeId: 'out-rejected-lead',
      caseId: 'case-no-evidence',
      disposition: 'rejected',
      recordedBy: 'human',
      recordedAt: '2026-09-29T21:00:00Z',
      rationale: 'No reproducible evidence',
    },
    {
      version: 1,
      outcomeId: 'out-accepted-paid',
      caseId: 'case-exact-in-scope',
      disposition: 'paid',
      recordedBy: 'human',
      recordedAt: '2026-09-12T09:00:00Z',
      receiptReference: 'file://receipts/fixture-receipt.txt',
      actualCostUsd: { amount: 0.75, source: 'provider_reported' },
    },
  ],
};

export const fixtureBundle: CaseBundle = parseCaseBundle(fixtureBundleJson);
